# This file is for various variables used throughout the workflow.
# Everything else regarding how things are run should go in the profile config, not here.
# See description of each setting in the README.md file.

input_dir: "nanopore_run_xyz123/fastq_pass"
output_dir: "output"
tmp_dir: "tmp"
log_dir: "logs"
db_fasta: "/databases/midas/MiDAS5.2_20231221/output/FLASVs.fa"
db_tax: "/databases/midas/MiDAS5.2_20231221/output/tax_complete_qiime.txt"
minalignlen: 400
minIDfrac: 0.95
filtlong_args: "--min_length 400 --min_mean_q 90"
max_threads: 16
