input_dir: "nanopore_run_xyz123/fastq_pass"
output_dir: "output"
tmp_dir: "tmp"
log_dir: "logs"
db_fasta: "db_fasta.fa"
db_tax: "db_tax.tsv"
minalignlen: 200
minIDfrac: 0.95
filtlong_args: "--min_length 400 --min_mean_q 90"
max_threads: 16

